//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public int FullNameId { get; set; }
        public int PositionId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Male { get; set; }
        public string Adress { get; set; }
    
        public virtual FullName FullName { get; set; }
        public virtual Position Position { get; set; }
        public virtual Group Group { get; set; }
    }
}
